language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing install
install:
  - echo "nothing needs to be installed"

# Scripts to be run
before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t simple-node .
  - docket tag simple-node xthian82/simple-node:$TRAVIS_JOB_ID

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push xthian82/simple-node:$TRAVIS_JOB_ID
